### ISSUE TITLE
ACI Simulator Startup Script Execution at Pod initialization

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/devnet-express-dci-issues#1]
Need to have the startup scripts for the ACI Simulator execute when the dCloud environment starts.  

Would like to have both the overall startup script, and the one for the ACI "Mission" run at startup so attendees won't need to do either.  

The dCloud team does this today in their other demos.  

@ecorban

**Comment by ecorban** [comment]
dcloud have been notified for this change.

**Comment by ecorban** [comment]
this baselining batch file for APIC  is executed from the workstation after bootup of workstation.

**Comment by movinalot** [comment]
This had been part of the DCI Pod startup since launch.
