### ISSUE TITLE
error message in NX-OS guestshell 

### ISSUE THREAD

**Issue by yawming** [CiscoDevNet/devnet-express-dci-issues#10]
https://learninglabs.cisco.com:8867/tracks/devnet-express-dci/dne-dci-intro-nx-os/dne-dci-intro-nxos-01_overview/step/4
Follow lab instruction run sample command, result is OK but with an error message 

nxosv1# run guestshell 
[admin@guestshell ~]$ dohost "sh lldp time | in Hold" "show cdp global"
**% Invalid command**
Global CDP information:
    CDP enabled globally
    Refresh time is 60 seconds
    Hold time is 180 seconds
    CDPv2 advertisements is enabled
    DeviceID TLV in System-Name(Default) Format

nxosv-2# run guestshell 
[guestshell@guestshell ~]$ dohost "sh lldp time | in Hold" "show cdp global"
**Bad Request**Global CDP information:
    CDP enabled globally
    Refresh time is 60 seconds
    Hold time is 180 seconds
    CDPv2 advertisements is enabled
    DeviceID TLV in System-Name(Default) Format

**Comment by yawming** [comment]
minor

**Comment by armartirosyan** [comment]
Fix has been pushed to the repo and has been staged.
