### ISSUE TITLE
guestshell - space in the path

### ISSUE THREAD

**Issue by yawming** [CiscoDevNet/devnet-express-dci-issues#11]
In this lab we the this instruction - [admin@guestshell ~]$ cd devnet-express-dci-code-samples/LM-5601 open-nxos/dne-dci-intro-nxos-02_onbox-programmability/

guestshell soen't like space in //LM-5601 open-nxos/, need to add a '*' or '?' to replace space when do the 'cd' command 

LL:
https://learninglabs.cisco.com:8867/tracks/devnet-express-dci/dne-dci-intro-nx-os/dne-dci-intro-nxos-02_onbox/step/3

**Comment by armartirosyan** [comment]
Fix has been pushed to the repo and has been staged.
