### ISSUE TITLE
wrong path for pictures in LL md file

### ISSUE THREAD

**Issue by yawming** [CiscoDevNet/devnet-express-dci-issues#12]
https://learninglabs.cisco.com:8867/tracks/devnet-express-dci/dne-dci-intro-nx-os/dne-dci-intro-nxos-04_devbox-and-visore/step/1

Picture is not displayed at the bottom of page

**Comment by yawming** [comment]
bug

**Comment by armartirosyan** [comment]
Fix has been pushed to the repo and has been staged.
