### ISSUE TITLE
Extra line in push_files.yml sample 

### ISSUE THREAD

**Issue by yawming** [CiscoDevNet/devnet-express-dci-issues#13]
The first line "----" should be removed

The playbook to complete the task looks like the following.

**----**
  ###########################################################
  #         Playbook to copy files to remote hosts          #
  ###########################################################
  - name: Retrieve facts from dCloud servers
    hosts: dcloud-servers

    tasks:
      - name: "Push new host file"
        copy:
          src: files/hosts
          dest: /etc/hosts
          owner: root
          group: root
          mode: 0644_

https://learninglabs.cisco.com:8867/tracks/devnet-express-dci/introduction-to-ansible/dne-dci-intro-ansible-03_ansible-hands-on/step/3

**Comment by armartirosyan** [comment]
This issue has been fixed.
