### ISSUE TITLE
Introduction to Ansible with NXOS - page2

### ISSUE THREAD

**Issue by yawming** [CiscoDevNet/devnet-express-dci-issues#14]
https://learninglabs.cisco.com:8867/tracks/devnet-express-dci/dne-dci-intro-nx-os/dne-dci-intro-nxos-06_ansible-nxapi/step/2

So far so good. Now, we can focus on setting up the Ansible control station.

**At here, maybe remind user to go to Ubuntu for the following ?**

Typically, inventory files and Ansible configuration files reside in /etc/ansible; however, for our example, we shall have required files in our local learning lab directory.

**Comment by armartirosyan** [comment]
Following line was added to the instructions

So far so good. Now, we can focus on setting up the Ansible control station.

**Now connect to Ubuntu host, if you have not done so already, and open command line terminal located on the desktop. When prompted, please use option 2 for `Python2.7` environment.**

Typically, inventory files and Ansible configuration files reside in /etc/ansible; however, for our example, we shall have required files in our local learning lab directory.
