### ISSUE TITLE
need to fix  the space in path - cd "\LM-1221 intro-python-xml\py-primer-2"

### ISSUE THREAD

**Issue by yawming** [CiscoDevNet/devnet-express-dci-issues#15]
https://learninglabs.cisco.com:8867/tracks/devnet-express-dci/devnet-express-python-xml-programming-basics/python-primer-2/step/2

**Comment by armartirosyan** [comment]
Replaced the path with `cd "./LM-1221\ intro-python-xml/py-primer-2"`
