### ISSUE TITLE
Missing DCI DevNet Track Repo - Introduction to Git - Page 2

### ISSUE THREAD

**Issue by lhercot** [CiscoDevNet/devnet-express-dci-issues#16]
On the Introduction to Git on Page 2, the DCI repo is not listed in the list as shown below.

<img width="1038" alt="screen shot 2017-06-16 at 00 29 40" src="https://user-images.githubusercontent.com/5236918/27204355-f4083df6-522a-11e7-982f-d10f79f9b41b.png">

DCI DevNet Track Repo should be added to the list.

Same for the list with the clone command on point (3).

<img width="1025" alt="screen shot 2017-06-16 at 00 32 24" src="https://user-images.githubusercontent.com/5236918/27204411-5776ec84-522b-11e7-9085-c95cfcb9889e.png">

**Comment by armartirosyan** [comment]
The images have been replaced with markdown rendered tables and path to the DCI code samples repo was added.
