### ISSUE TITLE
LM-1451 - Spelling error "Anisble"

### ISSUE THREAD

**Issue by EricThiel** [CiscoDevNet/devnet-express-dci-issues#17]
https://learninglabs.cisco.com/tracks/devnet-express-dci/introduction-to-ansible/dne-dci-intro-ansible-02_ansible-intro/step/3 has an instance where Ansible is Misspelled. Probably worth a grep of the full tree for "Anisble".

**Comment by armartirosyan** [comment]
Greped the entire module and only one instance had the `ansible` word misspelled. I fixed the typo.

Thank you
