### ISSUE TITLE
LM-5001 - wrong url prefix (should be https://)

### ISSUE THREAD

**Issue by EricThiel** [CiscoDevNet/devnet-express-dci-issues#18]
https://learninglabs.cisco.com/tracks/devnet-express-dci/devnet-express-dci-prep/dne-dci-prep-01/step/3

> Connect to your pod by opening a browser and navigating to port 8443 using http://

it should instead be https:// - the next line shows a correct example, but this line is misleading.

**Comment by armartirosyan** [comment]
Typo has been fixed.
