### ISSUE TITLE
Add Track Code Sample Repo to Windows and Ubuntu Jump Hosts

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/devnet-express-dci-issues#2]
The official code repo for all code samples in the track has been created and should be added to the gold image on both jump hosts.  Not many code samples are in there yet, but they will be added soon.  

We once migrated over from the old repo, we'll want to delete the "aci-learning-labs" repo from the jump hosts.  

The repo is at https://github.com/CiscoDevNet/devnet-express-dci-code-samples 

Please clone it into the `~/code` directory on both jump hosts, and configure the script to automatically clone down the latest contents at login (or boot up, whatever you're doing for DNA) 

@ecorban

**Comment by hpreston** [comment]
I have cloned the repo onto the Windows and Ubuntu jump hosts.  

I also deleted the `aci-learning-labs` repo from both hosts as those repos are no longer needed anymore.  

I also deleted the DNA code samples from the Ubuntu host as it isn't needed on that jump host any longer.  

Still need to configure both to automatically `git pull` the repo at login/bootup.

**Comment by ecorban** [comment]
On 'Still need to configure both to automatically git pull the repo at login/bootup.' we can use the  startup script for both host types from DNA.

**Comment by ecorban** [comment]
git clone working on windows. working on ubuntu.

**Comment by armartirosyan** [comment]
The `git pull` startup script successfully works on both Windows and Ubuntu hosts
