### ISSUE TITLE
Pre-Event Page 3 spelling errors

### ISSUE THREAD

**Issue by brbuxton** [CiscoDevNet/devnet-express-dci-issues#20]
https://learninglabs.cisco.com/tracks/devnet-express-dci/devnet-express-dci-prep/dne-dci-prep-01/step/3

"Connect to your pod by opening a browser and navigating to port 8443 using http://" should read "https://"

"find an shortcut" should read "find a shortcut"

"If it is not explicitly stated you can choose" should read "If it is not explicitly stated, you can choose"

"By using this process you will ensure" should read "By using this process, you will ensure"

**Comment by armartirosyan** [comment]
Typos have been fixed.

Thank you
