### ISSUE TITLE
Ansible spelling error

### ISSUE THREAD

**Issue by brbuxton** [CiscoDevNet/devnet-express-dci-issues#21]
https://learninglabs.cisco.com/tracks/devnet-express-dci/introduction-to-ansible/dne-dci-intro-ansible-02_ansible-intro/step/3

"wither" should read "either"

https://learninglabs.cisco.com/tracks/devnet-express-dci/introduction-to-ansible/dne-dci-intro-ansible-02_ansible-intro/step/4

"The webtier role; however, has playbooks" should use a comma instead of a semi-colon.

**Comment by armartirosyan** [comment]
Typos have been fixed.

Thank you
