### ISSUE TITLE
Excess backticks in code examples - "python-parsing-json-1"

### ISSUE THREAD

**Issue by nswiatec** [CiscoDevNet/devnet-express-dci-issues#23]
Code examples on [this page](https://learninglabs.cisco.com/tracks/devnet-express-dci/devnet-express-python-xml-programming-basics/python-parsing-json-1/step/2) have backtics before and after code examples. 

\`myvar={"donut":{"flavors":["chocolate","jelly","maple","plain"]}}`

**Comment by armartirosyan** [comment]
backtics have been removed from all code samples.

Thank you
