### ISSUE TITLE
Ansible Version Downgrade

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/devnet-express-dci-issues#24]
Due to bugs in Ansible 2.3 and the NX-OS modules, we need to downgrade the version of Ansible in the dCloud Pod to 2.2 on the Ubuntu workstation (and Windows if we have it installed there)  

This affects Lab and Mission for Intro to NX-OS.  Temporarily a note in the Learning Lab notifying students to downgrade to 2.2 is being added as a workaround.

**Comment by armartirosyan** [comment]
Temporarily note was added to all labs.

**Comment by movinalot** [comment]
Ansible 2.7.8 does not have an issue, have added upgrade to 2.7.8, no need to upgrade now
