### ISSUE TITLE
"Module Only" flag on Ansible Labs

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/devnet-express-dci-issues#25]
Several of the Ansible Learning Labs in the DNE DCI Module "Intro to ANsible" are showing up in the "Labs List" on Learning Labs.  All the DNE Labs should be "Module Only", and the Modules are "Track Only" to avoid students mistakenly getting into a lab they can't complete outside of an event.  

Also, this prevents duplicate labs from showing up in the list.

**Comment by armartirosyan** [comment]
MoudleOnly tag was added to all labs in devnet-express-dci-ansible module
