### ISSUE TITLE
ACI Toolkit Lab PreReq on Windows

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/devnet-express-dci-issues#26]
For lab page: https://learninglabs.cisco.com/tracks/devnet-express-dci/dne-dci-intro-aci/dne-dci-intro-aci-03_aci-toolkit/step/4 

The Windows host is missing the graphviz pre-reqs to run the diagram.py sample application.  Ideally we need to get these pre-reqs onto the Windows' workstation, but short term we can simply add a note to complete that exercise using the Ubuntu host only.

**Comment by annegentle** [comment]
The text has been fixed, closing.
