### ISSUE TITLE
Intermediate ACI Cobra Type-o

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/devnet-express-dci-issues#27]
https://learninglabs.cisco.com/tracks/devnet-express-dci/dne-dci-intermediate-aci/dne-dci-intermediate-aci-02_cobra/step/9 

Very final example has type in the code.  Should read:

```
$ python cobra_tenant.py -t Example -v Example_VRF, -b Example_BD, -g 10.10.1.1/24 -s public
```

**Comment by armartirosyan** [comment]
Typo has been fixed
