### ISSUE TITLE
dCloud Ubuntu Jump Host Updates

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/devnet-express-dci-issues#28]
Here are some updates for the Ubuntu host I'd like to have pulled into the next freeze 

* Shortcuts in the Chome Toolbar to match Windows (APIC, UCS, etc) 
* In the file explorer, provide a shortcut to the DCI directory (similar to on Windows) 
* Update shell prompt for terminal to assist with long paths and wrapping 
   * something like `export PS1="\w \n$ "` **before** activating the virtual environment would give the details needed and give a full line in the terminal for typing commands.  
  * This is similar to what is current on the Windows workstation

**Comment by annegentle** [comment]
Considered Done; closing.
