### ISSUE TITLE
Verify which infrastructure to use for ACI Programmbility module

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-dci-issues#29]
Need to verify that the following module uses the `Always-on ACI Sandbox`:

Module:
Intermediate ACI Programmability

**Comment by klevenstein** [comment]
Closing; lab hasn't been touched in two years. Will reopen if/when that lab gets updated.

https://github.com/CiscoDevNet/devnet-express-dci-intermediate-aci

**Comment by annegentle** [comment]
According to https://github.com/CiscoDevNet/sbx-intermediate-aci/blob/master/labs/sbx-intermediate-aci-01_aci-api/1.md it does use the Always-on Sandbox.
