### ISSUE TITLE
Ubuntu Jump Host "Start Python" Icons

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/devnet-express-dci-issues#3]
For consistency, can we get "Start Python2" and "Start Python3" icons on the Ubuntu desktop that startup with the relevant virtual environments.  

@ecorban

**Comment by armartirosyan** [comment]
I found the solution.

1. Create a file and name it `Start Python2.desktop` on the Desktop
2. Edit it with text editor and paste below code
  ```bash
[Desktop Entry]
Encoding=UTF-8
Name=Start Python2
TryExec=lxterminal
Exec=lxterminal -e "bash --rcfile /home/cisco/CiscoDevNet/venv/dci-py27-exercises/bin/activate"
Icon=lxterminal
Type=Application
Categories=GTK;Utility;TerminalEmulator;
Name[en_US]=Start Python2
Terminal=false
StartupNotify=false
```
3. Repeat the steps 1 and 2 for Python3

**Comment by annegentle** [comment]
This was marked done so I'm closing the Issue.
