### ISSUE TITLE
Need to update labs and slides to match the latest pod (not yet published)

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-dci-issues#30]
In meeting with Ruth, Paul, Iftach, and Anne on 01.23.18, we identified work needs to be done in order to make the new DCI pod available (a pod that Armen published a Gold image for on Jan 4), currently named:

  - Cisco DevNet Express DataCenter v2.2.1

On Jan 22, 2018, Pablo wrote:
> Done in RTP.
> If anyone else on this thread needs access, let me know and I’ll add you to the group.
> Use this link to schedule a session.
> https://dcloud2-rtp.cisco.com/schedule/399908/calendar?returnPathTitleKey=customcontent-schedule-calendar
> Pablo Mestre

**Comment by annegentle** [comment]
This has been fixed with the DCI v2 release.
