### ISSUE TITLE
Update the DCI pod to reset UCSD admin password 

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-dci-issues#31]
@movinalot (John D) noted the following:

> [John added content to the] Learning Labs in the UCSD module on how to reset the admin user password as well as reset the UCSD services.
> 
> It seems that UCSD Service reset is not always required which is great since it takes 30-40 minutes to reset them. However, if that is the case it would be good to reset the UCSD password and the services, if needed, a few hours prior to the module.

In a Spark room on Jan 24, Hank wrote:

> Armen recently ran several pod updates that were needed and had the dCloud team publish it out. We haven't gone live with it yet, but were planning in it after Barcelona. We can certainly pull back on that specific version, and add in this change, and anything else that we come up with that would be good/needed before we push the next full version out.

**Comment by austinMarcos** [comment]
This work should include appropriate updates to the slides:  the 'final published folder' for DCI is here: https://cisco.box.com/s/u4koex1mjlwxsnwlisc7jpq2fk1hdptj

**Comment by movinalot** [comment]
This module is now deprecated and not going to be offered as a DCI V2 Track or later
