### ISSUE TITLE
Update Pre-Event Preparation Sign Up For Account

### ISSUE THREAD

**Issue by movinalot** [CiscoDevNet/devnet-express-dci-issues#32]
Page 4
- I don't believe a CCO account is required any longer

- Asking attendees to get a DevNet account is not required, since they would not be able to read the Pre-Event Preparation lab if they did not have a DevNet Account

- Is it necessary for attendees to create a spark room at this point? It may not make much sense.

**Comment by annegentle** [comment]
I think these have been taken care of in v2 - feel free to re-open if that's not the case. Closing.
