### ISSUE TITLE
Pod url is invalid

### ISSUE THREAD

**Issue by EricThiel** [CiscoDevNet/devnet-express-dci-issues#34]
In the pod credentials, the pod looks something like http://v153user1:b47160@portal.vpod153.dc-05.com:8443/dcloud - but it should be https instead of http. I think this applies to all tracks, but definitely happening on DCI.

**Comment by patrickcisco** [comment]
I have pushed a change that will fix this for upcoming DCI events. I believe DNA events still use http.
