### ISSUE TITLE
Add Track Wide "requirements.txt" to Code Samples Directory

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/devnet-express-dci-issues#4]
Can we add the "requirements.txt" file for the entire module to the sample code repo https://github.com/CiscoDevNet/devnet-express-dci-code-samples to keep it with the code samples.  If there is a different one for python 2 vs python 3, just add them both and name them appropriately.

**Comment by annegentle** [comment]
Version 2 of the code has a requirements.txt - see https://github.com/CiscoDevNet/dciv2-code. Closing.
