### ISSUE TITLE
Incorrect APIC url and login info 

### ISSUE THREAD

**Issue by yawming** [CiscoDevNet/devnet-express-dci-issues#7]
https://learninglabs.cisco.com:8867/tracks/devnet-express-dci/dne-dci-intro-aci/dne-dci-intro-aci-01_understanding-aci/step/6

Current content on web site:
URL: https://apic1
User: admin
Password: password

Actual one should be:

URL: https://apic1.dcloud.cisco.com
User: admin
Password: C1sco12345

**Comment by armartirosyan** [comment]
The URL has been replaced with an IP address of the ACI server.
