### ISSUE TITLE
Adding path inormation for credentials.py

### ISSUE THREAD

**Issue by yawming** [CiscoDevNet/devnet-express-dci-issues#8]
It helps to navigate if we can add file path info for "credentials.py" in this page 
https://learninglabs.cisco.com:8867/tracks/devnet-express-dci/dne-dci-intro-aci/dne-dci-intro-aci-02_programmability-options/step/6

The path is 
~/CiscoDevNet/code/dci/LM-5551 intermediate-aci/dne-dci-intermediate-aci-01_aci-api 
in Ubuntu

~/code/devnet-express-dci-code-samples/LM-5551 intermediate-aci/dne-dci-intermediate-aci-01_aci-api
in Windows

**Comment by armartirosyan** [comment]
The path to  `credentials.py` script is the same for both Windows and Ubuntu. Please see below

Windows
```
Which Virtual Environment would you like to Activate?
 2. Python2
 3. Python3
>>> 2

Activating Virtual Environment for Python 2

(dci-py2-exercises) C:\Users\demouser\CiscoDevNet\code\dci
>cd "LM-5501 intro-aci\dne-dci-intro-aci-02_programmability-options\"

(dci-py2-exercises) C:\Users\demouser\CiscoDevNet\code\dci\LM-5501 intro-aci\dne-dci-intro-aci-02_programmability-options
>
```
 
Ubuntu
```
Which Virtual Environment would you like to activate?
2. Python2
3. Python3
>>> 2

Activating Virtual Environment for Python 2

(dci-py27-exercises) cisco@ubuntu:~/CiscoDevNet/code/dci$ cd LM-5501\ intro-aci/dne-dci-intro-aci-02_programmability-options/
(dci-py27-exercises) cisco@ubuntu:~/CiscoDevNet/code/dci/LM-5501 intro-aci/dne-dci-intro-aci-02_programmability-options$
```
