### ISSUE TITLE
dne-dci-intro-aci-03_aci-toolkit Exercise 3

### ISSUE THREAD

**Issue by yawming** [CiscoDevNet/devnet-express-dci-issues#9]
1. need to correct APIC URL:
$ python diagram.py -o heroes.png -t Heroes common
APIC login username: admin
APIC URL: https://apic
APIC Password:

2. got error when running script 

(dci-py2-exercises) C:\Users\demouser\CiscoDevNet\code\acitoolkit\applications\aci-diagram
>python diagram.py -o heroes.png -t Heroes common
APIC login username: admin
APIC URL: https://apic1.dcloud.cisco.com
APIC Password:
Processing tenant common

Drawing graph to heroes.png
Traceback (most recent call last):
  File "diagram.py", line 133, in <module>
    graph.draw(args.output, prog='dot')
  File "C:\Users\demouser\CiscoDevNet\venv\dci-py2-exercises\lib\site-packages\pygraphviz\agraph.py", line 1474, in draw
    data = self._run_prog(prog, args)
  File "C:\Users\demouser\CiscoDevNet\venv\dci-py2-exercises\lib\site-packages\pygraphviz\agraph.py", line 1308, in _run_prog
    runprog = r'"%s"' % self._get_prog(prog)
  File "C:\Users\demouser\CiscoDevNet\venv\dci-py2-exercises\lib\site-packages\pygraphviz\agraph.py", line 1295, in _get_prog
    raise ValueError("Program %s not found in path." % prog)
ValueError: Program dot not found in path.

(dci-py2-exercises) C:\Users\demouser\CiscoDevNet\code\acitoolkit\applications\aci-diagram
>

**Comment by armartirosyan** [comment]
Fixed.

gpraphviz needs to be added to PATH environment. Then  machine needs a reboot. 

![image](https://user-images.githubusercontent.com/7140657/33979049-823dfc22-e057-11e7-9c55-4bfd37a4ba81.png)

After that script is working as expected 
```
(dci-py2-exercises) C:\Users\demouser\CiscoDevNet\code\acitoolkit\applications\aci-diagram
>python diagram.py -o h.png -t Heroes common
APIC login username: admin
APIC URL: https://198.18.133.200
APIC Password:
Processing tenant common
Processing tenant Heroes


Drawing graph to h.png
```

I will work with Eddie to get this fix implemented in dCloud

**Comment by annegentle** [comment]
Considered fixed - and dcloud pod has been updated.
